name: Daily Animal Crawler

on:
  schedule:
    - [cite_start]cron: '0 0 * * *'  # 每天觸發一次 [cite: 5, 145, 148]
  [cite_start]workflow_dispatch:      # 允許手動觸發 [cite: 5, 152]

jobs:
  build:
    [cite_start]runs-on: ubuntu-latest [cite: 158, 161]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        [cite_start]uses: actions/checkout@v3 [cite: 168, 169]

      - name: Set up Python
        [cite_start]uses: actions/setup-python@v4 [cite: 174, 177]
        with:
          [cite_start]python-version: '3.10' [cite: 179]

      - name: Install dependencies
        [cite_start]run: pip install requests [cite: 188, 190]

      - name: Run script
        [cite_start]run: python api.py [cite: 193, 199]

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add animal_data.json
          git commit -m "Update animal data" || exit 0
          git push
